version: "3.4"
services:
  vue_project:
    container_name: vue_project
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./vue_project/:/var/www/html/app
    tty: true
